apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth-dpy
  labels:
    tier: ms-lab #microservices lab
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: auth
        tier: ms-lab
    spec:
      containers:
      - name: auth-api
        image: marknjo/ms-lab-auth
        imagePullPolicy: Never
        resources:
          limits:
            memory: "236Mi"
            cpu: "200m"
        env: 
          - name: PORT
            value: "3031"
          - name: HOST
            value: ticketing.dev
          - name: HOST_SRV
            value: ms-auth-srv
          - name: API_VERSION
            value: "1"
          - name: RUN_ENV
            value: "kubernetes"

        # readinessProbe:
        #   tcpSocket:
        #     port: 3031
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 3
        #   periodSeconds: 2
        #   failureThreshold: 1
        # livenessProbe:
        #   httpGet:
        #     port: 3031
        #     path: /health
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 3
        #   periodSeconds: 2
        #   failureThreshold: 1
        ports:
        - containerPort: 3031
---
apiVersion: v1
kind: Service
metadata:
  name: ms-auth-srv
  labels:
    tier: ms-lab
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - name: auth-api-pt
    protocol: TCP
    port: 3031
    targetPort: 3031