apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth-dpy
  labels:
    tier: ms-lab #microservices lab
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        tier: ms-lab
    spec:
      containers:
      - name: auth-api
        image: marknjo/ms-auth-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3031
---
apiVersion: v1
kind: Service
metadata:
  name: ms-auth-srv
  labels:
    tier: ms-lab
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - name: auth-api-pt
    protocol: TCP
    port: 3031
    targetPort: 3031

